name: smat_crow
description: AnyFarm Mobile Application

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.2.12+127
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ui_package:
    git:
      url: https://github.com/ummitahabib/ui_pckg/
      ref: package_ui     

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.0
  eva_icons_flutter: ^3.1.0
  one_context: ^2.1.0
  basic_utils: ^5.3.0
  date_time_format: ^2.0.1
  json_annotation: any
  http: ^0.13.5
  synchronized: ^3.0.0+3
  connectivity: ^3.0.6
  flutter_shimmer_widget: ^1.1.0
  intl: ^0.18.1
  otp_text_field: ^1.1.3
  google_fonts: ^4.0.3
  weather: ^3.0.0
  geolocator: ^9.0.1
  flutter_weather_bg_null_safety: ^1.0.0
  bubble_bottom_bar: ^2.0.0
  currency_text_input_formatter: ^2.1.5
  google_geocoding: ^0.2.0
  xml2json: ^6.2.0
  inapp_browser: ^1.0.2
  page_transition: ^2.0.9
  provider: ^6.0.3
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_crashlytics: ^3.1.1
  firebase_performance: ^0.9.1+1
  firebase_messaging: ^14.4.1
  google_sign_in: ^6.1.0
  font_awesome_flutter: ^10.2.1
  image_picker: ^1.0.1
  firebase_storage: ^11.1.1
  cloud_firestore: ^4.5.2
  lottie: ^2.3.2
  timeago: ^3.3.0
  google_maps_flutter: ^2.2.0
  enhanced_future_builder: ^2.0.0
  gpx: ^2.2.0
  path_provider: ^2.0.11
  flutter_local_notifications: ^15.1.0+1
  camera: ^0.10.0+1
  mailer: ^6.0.1
  syncfusion_flutter_charts: ^22.2.5
  image: ^4.0.15
  open_filex: ^4.3.1
  sensors: ^2.0.3
  flare_flutter: ^3.0.2
  flutter_compass: ^0.7.0
  location: ^5.0.1
  carousel_slider: ^4.1.1
  infinite_scroll_pagination: ^3.2.0
  double_back_to_close_app: ^2.1.0
  dio: ^5.1.1
  video_player: ^2.4.7
  circular_countdown_timer: ^0.2.2
  chewie: ^1.3.5
  fluttertoast: ^8.0.9
  get_it: ^7.3.0
  device_info: ^2.0.3
  image_cropper: ^4.0.1
  intl_phone_number_field: ^0.1.7
  open_mail_app: ^0.4.5
  url_launcher: ^6.1.5
  flutter_email_sender: ^6.0.1
  geojson_vi: ^2.2.0
  onboarding: ^3.1.0
  scroll_date_picker: ^3.7.0
  path: ^1.8.2
  firebase_analytics: ^10.2.2
  webview_flutter: ^2.0.1
  no_context_navigation: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  quiver: ^3.1.0
  freezed_annotation: ^2.1.0
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.3.6
  money_formatter: ^0.0.3
  skeletonizer: ^0.4.0
  google_maps_flutter_web: ^0.5.1
  flutter_native_splash: ^2.3.1
  pointer_interceptor: ^0.9.3+4
  awesome_dio_interceptor: ^1.0.0
  shared_preferences: ^2.2.0
  flutter_paystack:
  universal_html: ^2.2.3
  pie_chart: ^5.3.2
  beamer: ^1.5.6
  equatable: ^2.0.5
  marquee: ^2.2.3
  cached_network_image: ^3.3.0
  file_picker: ^5.5.0
  flutter_storage_path: ^1.0.4
  # story_view: 
  rxdart: ^0.27.7
  flutter_spinkit: ^5.2.0
  image_network: ^2.5.2
  record: ^4.4.4
  audioplayers: ^5.1.0
  permission_handler_web: ^0.0.2
  upgrader: ^6.4.0
  async: ^2.11.0
  uuid: ^3.0.7
  http_parser: ^4.0.2

#flutter packages pub run build_runner build --delete-conflicting-outputs
dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.1.0+1
  json_serializable: ^6.4.1
  hive_generator: ^2.0.0
  build_runner: ^2.2.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  web:
    generate: true
    image_path: "assets/launcher/icon.png"
    background_color: "#000000"

flutter:
  uses-material-design: true

  fonts:
    - family: regular
      fonts:
        - asset: fonts/regular.otf

    - family: semibold
      fonts:
        - asset: fonts/semibold.otf

    - family: Basier Circle
      fonts:
        - asset: fonts/BasierCircle-Regular.ttf

  assets:
    - assets/.
    - assets/icons/
    - assets/images/
    - assets/svgs/
    - assets/nsvgs/
    - assets/nsvgs/welcome/
    - assets/nsvgs/forgot_password/
    - assets/nsvgs/dashboard/
    - assets/nsvgs/ml/
    - assets/nsvgs/timeline/
    - assets/nsvgs/farm_tools/
    - assets/nsvgs/profile/
    - assets/nsvgs/subscription/
    - assets/launcher/
    - assets/flrs/
    - assets/shop_svgs/nav/
    - assets/animations/
    - assets/onboarding/
    - assets2/images/
    - assets2/svg/
    - assets2/shared/splash_assets/
    - assets2/shared/mail_logo.png
    - assets/images/
    - assets2/shared/dashboard_assets/
    - assets/images/desktop_ad_image.png

