// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvmgDTtNsa7yBFIvNAkVOBwD-2Ey9GJjI',
    appId: '1:681788757118:android:db5333d3e22c583901f42f',
    messagingSenderId: '681788757118',
    projectId: 'smatcrow',
    storageBucket: 'smatcrow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADsgZ6lsPoioTgBADaaYA8jjXKBiEcVoo',
    appId: '1:681788757118:ios:2bfb29a09a8b5ee801f42f',
    messagingSenderId: '681788757118',
    projectId: 'smatcrow',
    storageBucket: 'smatcrow.appspot.com',
    androidClientId: '681788757118-k5mbacqjki4r6qqfp0bb6h6mivkjivhk.apps.googleusercontent.com',
    iosClientId: '681788757118-10rmmgasa4m1hh905tua5nc6hbka0mah.apps.googleusercontent.com',
    iosBundleId: 'com.airsmat.smatcrows',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBG_Eetm88GuRxH_8Igs0r_xl_qZvaOU7M",
    authDomain: "smatcrow.firebaseapp.com",
    projectId: "smatcrow",
    storageBucket: "smatcrow.appspot.com",
    messagingSenderId: "681788757118",
    appId: "1:681788757118:web:b92c386282cdd34101f42f",
    measurementId: "G-FD03JJ1W5H",
  );
}
